# Generated by Django 5.2.6 on 2025-09-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('Linked List', 'Linked List'), ('Stack', 'Stack'), ('Queue', 'Queue'), ('Tree', 'Tree'), ('Graph', 'Graph'), ('DP', 'Dynamic Programming')], max_length=50)),
                ('status', models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_solved', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='Applied', max_length=20),
        ),
    ]
