# Generated by Django 5.2.6 on 2025-09-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dsaproblem_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('Quant', 'Quantitative Ability'), ('LR', 'Logical Reasoning'), ('DI', 'Data Interpretation'), ('Verbal', 'Verbal Ability')], max_length=20)),
                ('status', models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], default='Unsolved', max_length=10)),
                ('solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
