# Generated by Django 5.2.6 on 2025-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_aptitudequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudequestion',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
