# Generated by Django 5.2.6 on 2025-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_interviewsession_interviewquestion_resumedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='role',
            field=models.CharField(default='HR', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='max_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
