# Generated by Django 5.2.6 on 2025-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_interviewquestion_answer_interviewquestion_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='internships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
