# Generated by Django 5.2.6 on 2025-11-07 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_resumedata_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewsession',
            unique_together={('user', 'role')},
        ),
    ]
